<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MEDICINE.BAL\MEDICINE.BAL.csproj" />
    <ProjectReference Include="..\MEDICINE.COMMON\MEDICINE.COMMON.csproj" />
    <ProjectReference Include="..\MEDICINE.MODEL\MEDICINE.MODEL.csproj" />
    <ProjectReference Include="..\MEDICINE.REPOSITORY\MEDICINE.REPOSITORY.csproj" />
  </ItemGroup>

</Project>
